name: CI Pipeline with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub using GitHub Secrets
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: docker build -t sharmaatulkumar29/myimage11:latest .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: docker push sharmaatulkumar29/myimage11:latest

  run-tests:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # Step 5: Log in to Docker Hub using GitHub Secrets
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Step 6: Pull the Docker image from Docker Hub
      - name: Pull Docker Image
        run: docker pull sharmaatulkumar29/myimage11:latest

      # Step 7: Run the Docker container to execute tests
      - name: Run Playwright Tests
        run: docker run --rm sharmaatulkumar29/myimage11:latest
